### ISSUE TITLE
Unable to put more than 25 items

### ISSUE THREAD

**Issue by tuscland** [mapbox/dyno#94]
Hi!

For some reason, when using the `dyno scan ... | dyno put ...` idiom, I am usable to import more than 25 items in my dynamodn-local table. It is unclear to me why it happens, here is the stacktrace I got:

```
undefined:0


SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Function.Dyno.deserialize (/usr/local/lib/node_modules/dyno/index.js:76:16)
    at Transform.Parser.parser._transform (/usr/local/lib/node_modules/dyno/bin/cli.js:90:23)
    at Transform._read (_stream_transform.js:179:10)
    at Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Transform.Writable.write (_stream_writable.js:217:11)
    at Stream.ondata (stream.js:51:26)
    at Stream.emit (events.js:107:17)
```

Any idea?

Best,
Camille

**Comment by rclark** [comment]
Would it be possible for you to provide the file that `dyno scan` outputs? If there's sensitive data in there then we'll try and find another way to debug. Also, just to confirm, are you using the most recent tagged version of dyno (0.15.1)?

**Comment by tuscland** [comment]
Yes, it was version 0.15.1.
I'm sorry I can't share the `dyno scan` output.
Please check the pull-request that should solve this problem: https://github.com/mapbox/dyno/pull/98

**Comment by rclark** [comment]
Closed via https://github.com/mapbox/dyno/commit/53f5fbbd20b53571131818df7da640306e6bf348
